Changing Canvas.java
CenterForDigitalHumanities/TPEN28 pull request #662
Opened 2022-11-13 00:51 UTC by tvay11

Changing getLinesforProject in Canvas to update the annotationList.
<img width="746" alt="Screen Shot 2022-11-12 at 6 50 00 PM" src="https://user-images.githubusercontent.com/83725863/201500362-7767a2b9-6071-4c22-b7e7-45a0c26bb430.png">

2022-11-14 22:38 UTC, tvay11 commented
<img width="650" alt="Screenshot 2022-11-14 at 4 38 07 PM" src="https://user-images.githubusercontent.com/83725863/201782794-c2f597a4-f1d7-4fc4-bdfd-0d74bfa4f174.png">
I will still need to fix the label. I don't want a git merge problem in JSONhelper.

2022-11-16 20:53 UTC, tvay11 commented
![](https://user-images.githubusercontent.com/83725863/202291433-c97a1f41-454a-4c62-a53c-9bbc0e3b9f47.png)
Now, it has the right label.

2022-11-22 16:19 UTC, thehabes requested changes
Don't mix up presi2 and presi3!

In presi3, you need to be returning an `AnnotationPage` and this is the one whose `label`s need to be a language map.

In presi2, the `label` was already correct, so no changes are necessary.  The change you have made is a breaking change because you have changed the shape of the presentation 2 object other apps are expecting.

Remember that you have a two parter when taking on the AnnotationLists

- URI's like http://localhost:8080/TPEN/project/7211/annotations/13251387 should return the AnnotationList.
- You need a way to generate and return a Presentation 3 version of the AnnotationList for the Manifest.  You already know it will be an AnnotationPage and not a list.

In your PR, you should be clear about which part you are intending to accomplish.

2022-11-22 16:19 UTC, thehabes commented on src/java/edu/slu/tpen/entity/image/Canvas.java
> +        annotationList.element("label",buildLanguageMapOtherContent("en",canvasID));
`none` not `en`

2022-11-22 16:19 UTC, thehabes commented on src/java/edu/slu/tpen/entity/image/Canvas.java
> +        annotationList.element("target", canvasID);
Only in Presentation 3, this is a breaking change for Presentation 2.

2022-11-22 16:19 UTC, thehabes commented on src/java/edu/slu/tpen/entity/image/Canvas.java
> +        annotationList.element("items", resources_array);
Only in Presentation 3, this is a breaking change for Presentation 2.

2022-11-22 16:19 UTC, thehabes commented on src/java/edu/slu/tpen/entity/image/Canvas.java
> -        annotationList.element("@type", "sc:AnnotationList");
Prefixes stay in presentation 2.  In presentation 3, this is an `AnnotationPage` .

2022-11-22 16:19 UTC, thehabes commented on src/java/utils/JsonHelper.java
> +        public static JSONObject buildLanguageMapOtherContent(String language, String label)
You do not need this function.  There already exists a helper function that does what you need (build a language map with `none`

2023-02-03 18:32 UTC, markskroba requested changes

2023-02-03 18:32 UTC, markskroba commented on src/java/edu/slu/tpen/transfer/JsonLDExporter.java
> +            manifestData.put("items", pageList);
Here manifestData is called before being initialized, which causes 500 internal server error when requesting the manifest, so line `manifestData = new LinkedHashMap<>();` should be above this one

2023-02-03 18:32 UTC, markskroba commented on src/java/edu/slu/tpen/transfer/JsonLDExporter.java
> +            manifestData.put("items", pageList);
Also, putting `items` on manifestData so early makes it appear above everything else on the json, which makes it very different from how the old version looks.

2023-02-07 01:05 UTC, tvay11 commented
adding iiifv3 AnnotationPage in Canvas.java 
{
    "@context": "http://iiif.io/api/presentation/3/context.json",
    "id": "http://localhost:8080/TPEN/manifest/7211/manifest.json",
    "type": "Manifest",
    "label": {
        "none": [
            "Memorial Book of Pepo Albizzi"
        ]
    },
    "metadata": [
        {
            "label": {
                "en": [
                    "title"
                ]
            },
            "value": {
                "none": [
                    "Memorial Book of Pepo Albizzi"
                ]
            }
        },
        {
            "label": {
                "en": [
                    "subtitle"
                ]
            },
            "value": {
                "none": [
                    " "
                ]
            }
        },
        {
            "label": {
                "en": [
                    "msIdentifier"
                ]
            },
            "value": {
                "none": [
                    " "
                ]
            }
        },
        {
            "label": {
                "en": [
                    "msSettlement"
                ]
            },
            "value": {
                "none": [
                    " "
                ]
            }
        },
        {
            "label": {
                "en": [
                    "msRepository"
                ]
            },
            "value": {
                "none": [
                    " "
                ]
            }
        },
        {
            "label": {
                "en": [
                    "msIdNumber"
                ]
            },
            "value": {
                "none": [
                    " "
                ]
            }
        },
        {
            "label": {
                "en": [
                    "subject"
                ]
            },
            "value": {
                "none": [
                    " "
                ]
            }
        },
        {
            "label": {
                "en": [
                    "date"
                ]
            },
            "value": {
                "none": [
                    ""
                ]
            }
        },
        {
            "label": {
                "en": [
                    "language"
                ]
            },
            "value": {
                "none": [
                    ""
                ]
            }
        },
        {
            "label": {
                "en": [
                    "author"
                ]
            },
            "value": {
                "none": [
                    ""
                ]
            }
        },
        {
            "label": {
                "en": [
                    "description"
                ]
            },
            "value": {
                "none": [
                    " "
                ]
            }
        },
        {
            "label": {
                "en": [
                    "location"
                ]
            },
            "value": {
                "none": [
                    ""
                ]
            }
        },
        {
            "label": {
                "en": [
                    "msCollection"
                ]
            },
            "value": {
                "none": [
                    " "
                ]
            }
        }
    ],
    "canvases": [
        [
            {
                "id": "http://localhost:8080/TPEN/canvas/13251387",
                "type": "Canvas",
                "label": {
                    "none": [
                        "IP_001_001"
                    ]
                },
                "width": 749,
                "height": 1000,
                "items": {
                    "id": "http://localhost:8080/TPEN/annotations/13251387",
                    "type": "AnnotationPage",
                    "annotations": [
                        {
                            "@id": "http://localhost:8080/TPEN/project/7211/annotations/13251387",
                            "@type": "Annotation",
                            "label": {
                                "en": "http://localhost:8080/TPEN/canvas/13251387 List"
                            },
                            "target": "http://localhost:8080/TPEN/canvas/13251387",
                            "resource": [
                                {
                                    "@id": "http://localhost:8080/TPEN/line/104720616",
                                    "_tpen_line_id": "line/104720616",
                                    "@type": "AnnotationPage",
                                    "motivation": "oad:transcribing",
                                    "resource": {
                                        "@type": "cnt:ContentAsText",
                                        "cnt:chars": "This is the first line"
                                    },
                                    "on": "http://localhost:8080/TPEN/canvas/13251387#xywh=41,64,629,66",
                                    "_tpen_note": "",
                                    "_tpen_creator": 11,
                                    "modified": "2022-09-12 13:21:09.0"
                                },
                                {
                                    "@id": "http://localhost:8080/TPEN/line/104720617",
                                    "_tpen_line_id": "line/104720617",
                                    "@type": "AnnotationPage",
                                    "motivation": "oad:transcribing",
                                    "resource": {
                                        "@type": "cnt:ContentAsText",
                                        "cnt:chars": "This is the second line"
                                    },
                                    "on": "http://localhost:8080/TPEN/canvas/13251387#xywh=41,130,629,27",
                                    "_tpen_note": "",
                                    "_tpen_creator": 11,
                                    "modified": "2022-09-12 13:21:12.0"
                                },
                                {
                                    "@id": "http://localhost:8080/TPEN/line/104720618",
                                    "_tpen_line_id": "line/104720618",
                                    "@type": "AnnotationPage",
                                    "motivation": "oad:transcribing",
                                    "resource": {
                                        "@type": "cnt:ContentAsText",
                                        "cnt:chars": "This is the third line"
                                    },
                                    "on": "http://localhost:8080/TPEN/canvas/13251387#xywh=41,157,629,19",
                                    "_tpen_note": "",
                                    "_tpen_creator": 11,
                                    "modified": "2022-09-12 13:21:15.0"
                                },
                                {
                                    "@id": "http://localhost:8080/TPEN/line/104720619",
                                    "_tpen_line_id": "line/104720619",
                                    "@type": "AnnotationPage",
                                    "motivation": "oad:transcribing",
                                    "resource": {
                                        "@type": "cnt:ContentAsText",
                                        "cnt:chars": "This is the fourth line"
                                    },
                                    "on": "http://localhost:8080/TPEN/canvas/13251387#xywh=41,176,629,16",
                                    "_tpen_note": "",
                                    "_tpen_creator": 11,
                                    "modified": "2022-09-12 13:21:18.0"
                                },
                     [...]

2023-02-22 17:13 UTC, thehabes commented
I am merging this into oss-dev as completed via https://github.com/CenterForDigitalHumanities/TPEN28/pull/673

2023-02-22 17:14 UTC, merged