648 start to fill in services under constructor
CenterForDigitalHumanities/TPEN28 pull request #664
Opened 2022-11-16 20:23 UTC by Woodlnsoul

2022-12-01 05:46 UTC, Woodlnsoul commented
This is probably not near ready, but has a framework down. I will add comments in the next commit, I just wanted to get something up to look at.

2022-12-07 16:25 UTC, markskroba requested changes

2022-12-07 16:25 UTC, markskroba commented on src/java/edu/slu/tpen/transfer/JsonLDExporter.java
> +                logout.put("label", "End T-PEN Session");
This should also use buildNoneLanguageMap()

2022-12-07 16:25 UTC, markskroba commented on src/java/edu/slu/tpen/transfer/JsonLDExporter.java
> +               services.put("id","http://t-pen.org/TPEN/login.jsp");
From https://iiif.io/api/presentation/3.0/#services this should be `@id`

2022-12-07 16:25 UTC, markskroba commented on src/java/edu/slu/tpen/transfer/JsonLDExporter.java
> +               services.put("type",buildNoneLanguageMap("ImageService3"));
From https://iiif.io/api/presentation/3.0/#services this should be `type` and a value for it a string, not language map

2023-02-01 20:03 UTC, thehabes approved these changes
Looks good, confirm with Auth API documentation.

2023-02-01 20:04 UTC, markskroba approved these changes

2023-02-01 20:04 UTC, merged