Resolving Line URIs
CenterForDigitalHumanities/TPEN28 pull request #684
Opened 2023-03-23 04:34 UTC by DrewSadler01

2023-03-27 16:15 UTC, thehabes requested changes
You have the boilerplate code.  You need to make it Line specific and forget about the Folios and Canvases.

2023-03-27 16:15 UTC, thehabes commented on src/java/edu/slu/tpen/servlet/LineServlet.java
> +    protected void doGetUri(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
I think you are looking for [HTTPServlet's doGet](https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServlet.html) here,  which you intend to `@override`

2023-03-27 16:15 UTC, thehabes commented on src/java/edu/slu/tpen/servlet/LineServlet.java
> +        return "T-PEN Canvas Dereferencer";
Line not Canvas

2023-05-03 18:22 UTC, cubap commented on src/java/edu/slu/tpen/servlet/LineServlet.java
> +                  /*
too much comment. We've got versioning; just make it disappear.

2023-09-02 20:56 UTC, closed without merging