adding empty project checker
CenterForDigitalHumanities/TPEN28 pull request #690
Opened 2023-04-11 16:36 UTC by tvay11

<img width="1599" alt="Screenshot 2023-04-11 at 11 33 42 AM" src="https://user-images.githubusercontent.com/83725863/231229951-2a9b4488-f54d-4425-bda3-2822b3761383.png">

I am adding a checker to get a 404 error on an empty manifest.

2023-04-13 21:56 UTC, thehabes requested changes
Hi there,
The code is successful and looks good (but you have some System.outs to clean up).  It would be mergeable.  However,  we don't want to bring that .yaml file in.  You should be working on that in another branch.

2023-04-13 21:56 UTC, thehabes commented on src/java/edu/slu/tpen/servlet/ProjectServlet.java
> +                    System.out.println("Project 3");
Clean these commented and active System.out's, we would rather not deploy superfluous logs

2023-04-13 21:56 UTC, thehabes commented on src/java/textdisplay/Project.java
> +      System.out.println("not working");
remove pls

2023-04-26 18:46 UTC, thehabes approved these changes
Thanks for the clean up, looks good to go.

2023-04-27 16:06 UTC, markskroba approved these changes
Worked for me

2023-04-27 16:48 UTC, merged